import { db, auth, handleFirestoreError, OperationType } from "../firebase"; 
import { collection, addDoc, onSnapshot } from "firebase/firestore";

/**
 * Opens the Stripe Customer Portal for the current user.
 * This allows them to manage their subscription, payment methods, and billing history.
 */
export async function openCustomerPortal() {
  const user = auth.currentUser;

  if (!user) {
    console.error("User not authenticated. Cannot open customer portal.");
    return;
  }

  const path = `customers/${user.uid}/portal_sessions`;

  try {
    // 1. Create a document in the 'portal_sessions' sub-collection
    const portalRef = collection(db, 'customers', user.uid, 'portal_sessions');
    
    const docRef = await addDoc(portalRef, {
      return_url: window.location.origin + '/dashboard', // Where to send them back
    });

    // 2. Listen for the portal URL generated by the extension
    const unsubscribe = onSnapshot(docRef, (snap) => {
      const data = snap.data();
      if (data?.url) {
        unsubscribe();
        window.location.assign(data.url); // Redirect to Stripe's secure portal
      } else if (data?.error) {
        console.error(`Portal Error: ${data.error.message}`);
        unsubscribe();
      }
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, path);
      unsubscribe();
    });
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, path);
  }
}

/**
 * Creates a Stripe Checkout Session for a specific price ID.
 * This triggers the "Run Payments with Stripe" extension to generate a checkout URL.
 * @param priceId The Stripe Price ID to subscribe to
 */
export async function createSubscription(priceId: string) {
  const user = auth.currentUser;

  if (!user) {
    console.error("User not authenticated. Cannot create subscription.");
    return;
  }

  const path = `customers/${user.uid}/checkout_sessions`;

  try {
    // 1. Create a document in the 'checkout_sessions' sub-collection
    const checkoutRef = collection(db, 'customers', user.uid, 'checkout_sessions');
    
    const docRef = await addDoc(checkoutRef, {
      price: priceId,
      success_url: window.location.origin + '/success',
      cancel_url: window.location.origin + '/cancel',
      allow_promotion_codes: true,
      subscription_data: {
        trial_period_days: 7, // Explicitly set 7-day free trial
      },
    });

    // 2. Listen for the checkout URL generated by the extension
    const unsubscribe = onSnapshot(docRef, (snap) => {
      const data = snap.data();
      if (data?.url) {
        unsubscribe();
        window.location.assign(data.url); // Redirect to Stripe's secure checkout page
      } else if (data?.error) {
        console.error(`Checkout Error: ${data.error.message}`);
        unsubscribe();
      }
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, path);
      unsubscribe();
    });
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, path);
  }
}
