import React, { useState } from 'react';
import { motion } from 'motion/react';
import { 
  Check, 
  Sparkles, 
  Zap, 
  Shield, 
  Clock, 
  ArrowRight,
  RefreshCw 
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { db } from '../firebase';
import { doc, updateDoc, collection, addDoc, onSnapshot } from 'firebase/firestore';
import { addDays } from 'date-fns';

const Pricing: React.FC = () => {
  const { user, profile } = useAuth();
  const [loading, setLoading] = useState<string | null>(null);

  const handleSubscribe = async (plan: 'monthly' | 'yearly') => {
    if (!user) {
      alert("Please sign in to subscribe.");
      return;
    }
    setLoading(plan);
    
    // FIXED: Removed trailing comma and stripped whitespace from Price IDs
    const priceId = plan === 'monthly' 
      ? "price_1TFLdKBMbxh6jv0C0MIn4aU5" 
      : "price_1TFLeCBMbxh6jv0Clh2Evj4b";

    try {
      // Ensure the path matches your extension configuration exactly
      const checkoutSessionsRef = collection(db, 'customers', user.uid, 'checkout_sessions');
      
      const docRef = await addDoc(checkoutSessionsRef, {
        price: priceId,
        success_url: window.location.origin + '/success',
        cancel_url: window.location.origin + '/cancel',
        mode: 'subscription', 
        subscription_data: {
          trial_period_days: 7, // Configures the 7-day trial
        },
        allow_promotion_codes: true,
      });

      // Listen for the checkout URL generated by the Firebase extension
      const unsubscribe = onSnapshot(docRef, (snap) => {
        const data = snap.data();
        
        if (data?.url) {
          unsubscribe(); 
          window.location.assign(data.url);
        } else if (data?.error) {
          // Handle extension-side errors (e.g., invalid Stripe key)
          console.error(`Stripe Extension Error: ${data.error.message}`);
          unsubscribe();
          setLoading(null);
        }
      });
    } catch (err) {
      console.error("Firestore write error:", err);
      setLoading(null);
    }
  };

  const plans = [
    {
      id: 'monthly',
      name: 'Monthly Pro',
      price: '$6.99',
      period: '/month',
      description: 'Perfect for individuals and small projects.',
      features: ['Unlimited AI Writing', 'Full SaaS Dashboard Access', '10GB Storage', 'Priority Support'],
      buttonText: 'Subscribe Monthly',
      color: 'bg-blue-600'
    },
    {
      id: 'yearly',
      name: 'Yearly Pro',
      price: '$69.99',
      period: '/year',
      description: 'Best value for long-term builders.',
      features: ['Everything in Monthly', '2 Months Free', '50GB Storage', 'Early Access to New Features'],
      buttonText: 'Subscribe Yearly',
      color: 'bg-indigo-600',
      popular: true
    }
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 p-8 flex flex-col items-center justify-center">
      <div className="max-w-5xl w-full space-y-12">
        <div className="text-center space-y-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="inline-flex items-center gap-2 px-4 py-1.5 bg-blue-900/30 border border-blue-500/30 rounded-full text-blue-400 text-sm font-bold"
          >
            <Sparkles size={16} /> Subscription Required
          </motion.div>
          <h1 className="text-5xl font-extrabold tracking-tight">Your Trial Has Expired</h1>
          <p className="text-slate-500 text-xl max-w-2xl mx-auto">
            Choose a subscription plan to continue using MUBUSLINK AI's professional tools and magic writing experience.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {plans.map((plan) => (
            <motion.div
              key={plan.id}
              whileHover={{ y: -10 }}
              className={`relative p-10 rounded-3xl border bg-slate-900 shadow-xl transition-all ${
                plan.popular ? 'border-blue-500 ring-2 ring-blue-500/20' : 'border-slate-800'
              }`}
            >
              {plan.popular && (
                <div className="absolute -top-4 left-1/2 -translate-x-1/2 px-4 py-1 bg-blue-600 text-white text-xs font-bold rounded-full uppercase tracking-wider">
                  Most Popular
                </div>
              )}
              <div className="space-y-6">
                <div>
                  <h3 className="text-2xl font-bold">{plan.name}</h3>
                  <p className="text-slate-500 text-sm mt-1">{plan.description}</p>
                </div>
                <div className="flex items-baseline gap-1">
                  <span className="text-5xl font-extrabold">{plan.price}</span>
                  <span className="text-slate-500 font-medium">{plan.period}</span>
                </div>
                <ul className="space-y-4">
                  {plan.features.map((feature, i) => (
                    <li key={i} className="flex items-center gap-3 text-sm text-slate-300">
                      <div className="shrink-0 w-5 h-5 bg-emerald-900/20 text-emerald-500 rounded-full flex items-center justify-center">
                        <Check size={12} />
                      </div>
                      {feature}
                    </li>
                  ))}
                </ul>
                <button
                  onClick={() => handleSubscribe(plan.id as 'monthly' | 'yearly')}
                  disabled={!!loading}
                  className={`w-full py-4 rounded-2xl font-bold text-lg transition-all flex items-center justify-center gap-2 shadow-lg ${
                    plan.popular 
                      ? 'bg-blue-600 hover:bg-blue-700 text-white shadow-blue-900/20' 
                      : 'bg-slate-800 hover:bg-slate-700 text-white'
                  }`}
                >
                  {loading === plan.id ? <RefreshCw className="animate-spin" /> : <Zap size={20} />}
                  {plan.buttonText}
                </button>
              </div>
            </motion.div>
          ))}
        </div>

        <div className="text-center space-y-4">
          <div className="flex items-center justify-center gap-8 text-slate-500">
            <div className="flex items-center gap-2"><Shield size={16} /> Secure Stripe Payment</div>
            <div className="flex items-center gap-2"><Clock size={16} /> Cancel Anytime</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Pricing;
